### ISSUE TITLE
Option to select GIPHY stickers

### ISSUE THREAD

**Issue by pribeh** [Thanasis1101/react-native-gif-search#6]
Is there are way to use giphyApiProps to select stickers in the search results? It looks like gifs are hardcoded into the base url here `GIPHY_BASE_URL = 'https://api.giphy.com/v1/gifs/'` in line 18 of https://github.com/Thanasis1101/react-native-gif-search/blob/master/src/GifSearch.js

If we could remove gifs from the GIPHY_BASE_URL = 'https://api.giphy.com/v1/' and then add it as a props with a default set to /gifs that would be great. It looks like we would have to adjust fetchGiphyGifs (line 212) to make it work but I'm not sure how.

```
fetchGiphyGifs = (endpoint) => {
      var limit = Math.min(this.gifsToLoad, this.maxGifsToLoad - this.state.offset)
      if (this.provider == providers.ALL) { 
          limit = Math.floor(limit/2)
      }
    
      if (endpoint == endpoints.TRENDING) {

          return Requests.fetch("GET", GIPHY_BASE_URL + "trending", {
              "api_key": this.giphyApiKey,
              "limit": limit,
              "rating": "pg",
              "offset": this.state.offset,
              ...this.props.giphyApiProps,
          })

      } else if (endpoint == endpoints.SEARCH) {

          return Requests.fetch("GET", GIPHY_BASE_URL + "search", {
              "api_key": this.giphyApiKey,
              "q": this.state.search_term,
              "limit": limit,
              "rating": "pg",
              "offset": this.state.offset,
              ...this.props.giphyApiProps,
          })

      }
  }
```

**Comment by Thanasis1101** [comment]
Yes, that was a thought for later updates. Since there is a request, I will try to include an option for the stickers, when I have some free time. Perhaps I will also add a tab-like UI for switching between stickers and gifs, but also have the option for choosing only one of them. I will let you know when the update is released. Thanks for showing interest !

**Comment by Thanasis1101** [comment]
Version `1.1.2` is now out including the stickers ! The property `gifType` was added and you can choose between `"gifs"`, `"stickers"` and `"all"` (two buttons to switch between gifs and stickers). Many more new properties where added for changing the style and text for gifs and stickers, so make sure to read the [README.md](https://github.com/Thanasis1101/react-native-gif-search/blob/master/README.md) especially in [Version History](https://github.com/Thanasis1101/react-native-gif-search/blob/master/README.md#version-history) and [Properties](https://github.com/Thanasis1101/react-native-gif-search/blob/master/README.md#properties), in order to find out the new possibilities. Also the example [App.js](https://github.com/Thanasis1101/react-native-gif-search/blob/master/example/App.js) was updated to include an example with both gifs and stickers.

Hope you find it useful !

**Comment by pribeh** [comment]
@Thanasis1101 That's awesome. Thanks so much for adding it. I'll test it tomorrow.

**Comment by Thanasis1101** [comment]
@pribeh Sure, test it and give some feedback.
You can also star the repo if you find it useful.
